// 8 大黄金爆款示范模板库 (完全符合 No Brand Leakage & 5步全链路完整性)
export const defaultPresets: Array<[string, string, string, string, string, string, string, string]> = [
  // 1. preset_3s_hook (对应 李响-005.MOV)
  [
    'preset_3s_hook',
    '3秒反差惊悚吸睛',
    '3秒惊悚反差',
    '对应《李响-005.MOV》实战拆解：前3秒惊悚反差Hook抓完播，高润泽质感打泡，SGS数据标红，结尾强挂车',
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/sample_3s_hook.mp4',
          platform: 'douyin',
          bloggerType: 'skincare_expert',
          viralReason: '前3秒惊悚视觉Hook + 高润泽膏体打泡 + SGS数据标红',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '冷白光皮肤测评实验室，博主惊恐表情与吸油纸黑头测试镜头',
          subject: '博主手持 [Product] 展示惊人洗净反差',
          style: '抖音爆款惊悚反差风',
          palette: ['#FF2D55 警示红', '#1A1A1A 极夜黑', '#00E5FF 科技蓝'],
          lighting: '环形高亮冷白光，面部细节与油脂瑕疵极其清晰',
          composition: '前3秒极近面部特写 -> 黄金三分法 product close-up',
          mood: '惊悚吸睛反差，强求知欲望',
          camera: '快速推镜头 (Fast Zoom In) + 极速镜头切变',
          static_image_prompt: 'split screen photo testing skin oil and blackheads, shocked expression holding [Product], ring light reflections, text overlay graphics, 4k ultra detailed',
          rationale: '根据《李响-005.MOV》实战拆解：前3秒惊悚情绪抓取完播率，中段膏体细密打泡建立信任，SGS标红数据促成挂车转化',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '3.0s', shotType: '近景特写', cameraMovement: '快速推镜头', description: '博主惊恐表情，撕开吸油纸高呼脸部危机 Hook', mood: '惊悚吸睛' },
            { shotIndex: 2, startTime: '3.0s', endTime: '12.0s', shotType: '特写', cameraMovement: '微距慢特写', description: '[Product] 挤出膏体与拉丝打泡过程', mood: '细腻质感' },
            { shotIndex: 3, startTime: '12.0s', endTime: '35.0s', shotType: '中景', cameraMovement: '平移', description: '全脸揉搓洗脸与清水面部冲洗特写', mood: '舒爽沉浸' },
            { shotIndex: 4, startTime: '35.0s', endTime: '65.0s', shotType: '特写', cameraMovement: '静态特写', description: 'SGS 8小时控油-66.87% 报告大字标红展示', mood: '权威硬核' },
            { shotIndex: 5, startTime: '65.0s', endTime: '86.8s', shotType: '近景', cameraMovement: '前推', description: '博主手持 [Product] 引导点击左下角挂车', mood: '强转化' },
          ],
          videoStructure: { totalShots: 5, avgShotDuration: '17.36s', pacing: 'fast', narrativeArc: '3秒惊悚 Hook -> 膏体打泡展示 -> 全脸冲洗实测 -> SGS数据标红 -> 左下角挂车引导', hookTiming: '前3秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“天呐千万别乱洗了！你脸上的油脂黑头都快溢出来了...”', sellingPoints: ['3秒惊悚视觉Hook', '高润泽质感拉丝', 'SGS 8小时控油-66.87%'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '128', musicStyle: '128BPM重低音Trap' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'split screen photo testing skin oil...',
          imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
          videoTone: 'douyin_beat',
          durationSec: 5,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'zoom_in',
          motion_intensity: 'strong',
          motion_description: '前3秒镜头快速前推至面部吸油纸，随后滑过 [Product] 膏体打泡过程',
          duration_sec: '5',
          video_prompt: 'A high tension fast zoom-in shot, sudden contrast 3s hook, creamy [Product] texture lathering into dense bubbles, studio lighting, cinematic 60fps',
          audio_layer: '重低音Trap + 惊悚卡点音效',
          negative_prompt: '避免画质模糊，避免镜头晃动',
          isMultiShot: true,
          shotPrompts: [
            'Fast camera zoom in on shocked expression holding blot paper',
            'Macro close up of [Product] texture squeezing and foaming',
            'Medium shot of face washing and water splash rinsing',
            'Static close up of official SGS test report with glowing red numbers',
            'Forward camera movement on product with banner graphics',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'A high tension fast zoom-in shot...', targetPlatform: 'douyin', scriptPersona: '成分党' },
        output: {
          title: '千万别乱洗了！前3秒把我吓出一身汗！😱',
          hook: '你以为脸洗干净了？看看吸油纸下的真相！',
          body: '别再傻傻用清水洗脸了！每次用 [Product]，深层揉搓出奶油般绵密泡沫...\n\nSGS 权威机构实测 8小时控油达 -66.87%，14天黑头减少 -35.92%！洗完整天哑光清爽，完全不紧绷！',
          hashtags: ['#控油洗面奶', '#SGS实测', '#油皮救星', '#爆款测评'],
          cta: '点击左下角小黄车，领买一送一专属补贴！',
          platform_fit: {
            douyin: '油皮炸裂推荐！SGS权威机构认证：8小时控油-66.87%！[Product] 现在买一送一！速抢！',
            xiaohongshu: '前3秒真相警示！[Product] 不只是控油，细腻泡沫温和不伤肤，大油田洗完真的会谢！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '千万别乱洗了！前3秒把我吓出一身汗！😱', tonePreference: '卡点', commercialScenario: '抖音/小红书商业化' },
        output: {
          bgm_recommendation: {
            track_name: 'Trap Tech Beat 128BPM',
            artist: 'Phonk Master',
            style: ['卡点Electronic', '重低音Trap'],
            bpm: '128',
            mood_match: '128BPM重低音卡点，精准切合前3秒惊悚Hook与打泡节奏',
            sync_point: '0.8s(惊悚Hook), 3.0s(打泡特写), 4.5s(SGS标红)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'EDM Drop Bass Boost', style: '强重低音', when_to_use: '适合极致快节奏卡点' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '黄字黑边' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 3.0, action: 'subtitle_in', text: '“天呐千万别乱洗了！脸上的油脂黑头都溢出来了...”', position: 'bottom_center' },
            { at: '3.0s', startSec: 3.0, endSec: 12.0, action: 'subtitle_in', text: '每次用 [Product] 挤出奶油般绵密泡沫...', position: 'bottom_center' },
            { at: '12.0s', startSec: 12.0, endSec: 35.0, action: 'subtitle_in', text: 'SGS 权威实测：8小时控油 -66.87%', position: 'bottom_center' },
            { at: '35.0s', startSec: 35.0, endSec: 65.0, action: 'brand_stamp', text: 'SGS 权威检测认证', position: 'top_right' },
            { at: '65.0s', startSec: 65.0, endSec: 86.8, action: 'subtitle_in', text: '点击左下角领专属买一送一福利！', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_3s_hook.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 86.8 },
          qa_checklist: ['✓ 前3秒惊悚Hook卡点明确', '✓ SGS控油数据字幕明显标红', '✓ 零品牌泄漏，使用通用产品变量'],
        },
      },
    }),
    'douyin',
    'preset_3s_hook',
  ],

  // 2. preset_before_after (对应 赖雨华-0701.mp4)
  [
    'preset_before_after',
    '清水 vs 产品对比冲击',
    '清水对比冲击',
    '对应《赖雨华-0701.mp4》实战拆解：左右分屏实验对比，清水洗脸局限 vs 吸油纸哑光证明',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/赖雨华-0701-40-清水洗脸24.mp4',
          platform: 'douyin',
          bloggerType: 'skincare_expert',
          viralReason: '左右分屏实验对比 + 吸油纸压脸实测 + 直观数据视觉',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '左右分屏实验对比台，左侧清水洗脸，右侧 [Product] 洗脸',
          subject: '吸油纸压脸测试，清水侧满油湿透，[Product] 侧干爽哑光',
          style: '硬核实验对比风',
          palette: ['#00E5FF 科技蓝', '#FF3B30 警告红', '#FFFFFF 哑光白'],
          lighting: '双侧侧光，清晰凸显面部出油光泽与无油哑光对比',
          composition: '左右 1:1 分屏，中线带发光 HUD 动效',
          mood: '震撼反差，理智劝退清水党',
          camera: '左右横移 (Pan Left/Right) 极速平移',
          static_image_prompt: 'split screen camera, left half wet oily face with blue blot paper soaked, right half clean matte face holding [Product], laboratory lighting, 4k ultra detailed',
          rationale: '根据《赖雨华-0701.mp4》实战拆解：清水洗脸是很多人的误区，通过吸油纸实验建立极强视觉反差',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '5.0s', shotType: '中景分屏', cameraMovement: '左右扫摄', description: '左右分屏：左侧清水洗脸，右侧 [Product] 洗脸对比 Hook', mood: '反差震撼' },
            { shotIndex: 2, startTime: '5.0s', endTime: '25.0s', shotType: '特写', cameraMovement: '镜头推进', description: '吸油纸按压额头，左侧变深湿透，右侧干爽洁净', mood: '实验说服' },
            { shotIndex: 3, startTime: '25.0s', endTime: '55.0s', shotType: '微距', cameraMovement: '平移', description: '[Product] 三重矿物泥膏体洗去毛孔老废角质特写', mood: '原理剖析' },
            { shotIndex: 4, startTime: '55.0s', endTime: '88.0s', shotType: '近景', cameraMovement: '推近', description: '最终哑光无油全脸效果与优惠挂车指引', mood: '挂车成交' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '22.0s', pacing: 'medium', narrativeArc: '左右分屏对比 -> 吸油纸实测真相 -> 矿物泥深层原理 -> 哑光全脸挂车', hookTiming: '前5秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“清水洗脸24小时后...看看吸油纸下的真相吧！”', sellingPoints: ['左右分屏吸油纸实验', '14天出油减少 -35.28%', '哑光干爽不紧绷'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '115', musicStyle: '硬核测评节奏' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'split screen photo testing skin oil...',
          imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
          videoTone: 'douyin_beat',
          durationSec: 5,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'pan_left',
          motion_intensity: 'strong',
          motion_description: '镜头从左侧油光脸快扫至右侧 [Product] 哑光脸，带发光 HUD 动效',
          duration_sec: '5',
          video_prompt: 'Fast whip pan shot split screen left oily forehead right clean matte skin with [Product], glowing HUD graphics, cinematic 60fps',
          audio_layer: '重低音卡点 + 机械扫频音效',
          negative_prompt: '避免分屏线对不齐，避免面部反光过度',
          isMultiShot: true,
          shotPrompts: [
            'Split screen camera whip pan from oily face to clean matte skin',
            'Macro close up of blot paper pressed on forehead showing oil absorption',
            'Microscope animation of mineral clay lifting excess sebum',
            'Forward push on model smiling with fresh matte glow skin',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'Fast whip pan shot split screen...', targetPlatform: 'douyin', scriptPersona: '成分党' },
        output: {
          title: '清水洗脸24小时后...左右脸对比太震撼了！💥',
          hook: '你以为用清水洗脸最安全？吸油纸一贴全是油！',
          body: '做个真实实验！左脸只用清水洗，右脸用 [Product]...\n\n5分钟后吸油纸一贴，清水组油光满满，[Product] 组干爽哑光！SGS 实测 14 天出油减少 -35.28%！',
          hashtags: ['#清水洗脸误区', '#控油实验', '#SGS权威检测', '#油皮必看'],
          cta: '点击下方链接，领专属折扣卷！',
          platform_fit: {
            douyin: '大油田避坑！清水洗脸只会越洗越油！试试 [Product]，SGS实测出油-35.28%！速抢！',
            xiaohongshu: '清水洗脸大翻车！左右脸吸油纸实验证明：[Product] 才是油皮真爱～',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '清水洗脸24小时后...左右脸对比太震撼了！💥', tonePreference: '卡点', commercialScenario: '抖音/小红书商业化' },
        output: {
          bgm_recommendation: {
            track_name: 'Rhythmic Energy Pulse',
            artist: 'Dynamic Sound',
            style: ['商业卡点', '硬核节奏'],
            bpm: '115',
            mood_match: '强有力打击乐，卡点左右分屏对比与吸油纸按压瞬间',
            sync_point: '1.0s(分屏对比), 4.5s(吸油纸按压)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Trap Tech Beat 128BPM', style: '重低音Trap', when_to_use: '适合极致快节奏' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '黄字黑边' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 5.0, action: 'subtitle_in', text: '“清水洗脸24小时后...看看吸油纸下的真相吧！”', position: 'bottom_center' },
            { at: '5.0s', startSec: 5.0, endSec: 25.0, action: 'subtitle_in', text: '吸油纸按压：清水组油光满面，[Product] 组干爽哑光！', position: 'bottom_center' },
            { at: '25.0s', startSec: 25.0, endSec: 55.0, action: 'subtitle_in', text: 'SGS 权威实测：14天出油减少 -35.28%', position: 'bottom_center' },
            { at: '55.0s', startSec: 55.0, endSec: 88.0, action: 'subtitle_in', text: '点击下方小黄车，领买一送一活动！', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_before_after.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 88.0 },
          qa_checklist: ['✓ 左右分屏对比清晰', '✓ 吸油纸实验音画卡点精准', '✓ 零品牌泄漏'],
        },
      },
    }),
    'douyin',
    'preset_before_after',
  ],

  // 3. preset_morning_routine (对应小红书晨间护肤)
  [
    'preset_morning_routine',
    '治愈晨间 Routine 沉浸',
    '治愈晨间Routine',
    '小红书爆款风格：柔和晨间自然光、高润泽肌感与沉浸式洗护 Vlog，低饱和治愈 Lofi 氛围',
    'https://images.unsplash.com/photo-1512290900673-7002fffe929a?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'https://images.unsplash.com/photo-1512290900673-7002fffe929a?auto=format&fit=crop&w=600&q=80',
          platform: 'xiaohongshu',
          bloggerType: 'daily_seeding',
          viralReason: '晨间自然光 + 高润泽膏体拉丝 + 沉浸式 Lofi 音效',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '晨间阳光透入浴室百叶窗，高润泽洁面膏体与水滴交融',
          subject: '纤手持 [Product] 挤出冰淇淋般丝滑膏体',
          style: '小红书治愈生活风',
          palette: ['#A8D5BA 柔绿', '#FFFFFF 纯白', '#F5F5F0 暖白'],
          lighting: '晨间柔和自然阳光，带柔光微光晕',
          composition: '对角线构图 + 45度俯拍特写',
          mood: '清爽治愈，晨间精致仪式感',
          camera: '45度俯拍慢推 + 大光圈背景虚化',
          static_image_prompt: 'a young woman holding [Product] in bright sunny bathroom, morning sunlight through white blinds, creamy texture visible, soft focus lifestyle photo, 8k resolution',
          rationale: '小红书爆款=真实晨间场景+润泽肌感+低饱和治治愈色调',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '4.0s', shotType: '中景', cameraMovement: '慢推', description: '晨光穿透百叶窗，博主取下 [Product] 开始晨间 Routine', mood: '治愈唤醒' },
            { shotIndex: 2, startTime: '4.0s', endTime: '15.0s', shotType: '特写', cameraMovement: '微距慢特写', description: '挤出冰淇淋般细腻膏体与拉丝打泡特写', mood: '触感沉浸' },
            { shotIndex: 3, startTime: '15.0s', endTime: '30.0s', shotType: '近景', cameraMovement: '固定镜头', description: '极细腻泡沫包覆面部，轻柔按摩沉浸 SPA', mood: '舒缓享受' },
            { shotIndex: 4, startTime: '30.0s', endTime: '45.0s', shotType: '近景', cameraMovement: '轻微上抬', description: '冲洗后肌肤水润透亮，展现自然健康微光', mood: '清爽透亮' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '11.25s', pacing: 'slow', narrativeArc: '晨光唤醒 -> 膏体细腻触感 -> 泡沫包覆SPA -> 清爽亮泽呈现', hookTiming: '前4秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“大油田的晨间快乐水！挤出来是冰淇淋泥膏🍃”', sellingPoints: ['晨间治愈仪式感', '冰淇淋泥膏质感', 'SGS 8小时控油-66.87%'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '82', musicStyle: '治愈Lofi钢琴' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'a young woman holding [Product]...',
          imageUrl: 'https://images.unsplash.com/photo-1512290900673-7002fffe929a?auto=format&fit=crop&w=600&q=80',
          videoTone: 'xiaohongshu_healing',
          durationSec: 4,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'zoom_in',
          motion_intensity: 'subtle',
          motion_description: '镜头缓慢向前推进至 [Product] 膏体挤出瞬间，阳光光斑在瓶身上缓慢流动',
          duration_sec: '4',
          video_prompt: 'A slow smooth zoom-in shot, camera moves closer to [Product] tube, gentle push of creamy cleanser emerging, morning light flickering, 60fps slow motion',
          audio_layer: '晨间水滴声 + 柔和 Lofi 钢琴',
          negative_prompt: '避免镜头摇晃，避免画面色彩过艳',
          isMultiShot: true,
          shotPrompts: [
            'Slow zoom in on [Product] held near sunny window',
            'Macro shot of creamy cleanser texture squeezing out gently',
            'Soft focus close up of rich lather on wet skin with water droplets',
            'Tilt up on fresh bright face with natural skin glow',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'A slow smooth zoom-in shot...', targetPlatform: 'xiaohongshu', scriptPersona: '油皮亲妈' },
        output: {
          title: '大油田的晨间快乐水！挤出来是冰淇淋泥膏🍃',
          hook: '夏天早上起来脸像喷油池？试试这晨间清爽 SPA！',
          body: '每次用 [Product]，像给毛孔做了一场冰爽 SPA！\n\n温和植萃与三重矿物泥结合，SGS 实测 8小时控油达 -66.87%！不仅控油还不紧绷，洗完脸水嫩透亮～',
          hashtags: ['#晨间护肤', '#控油洗面奶', '#治愈系Vlog', '#油皮救星'],
          cta: '油皮姐妹快试试，真的会爱上洗脸的感觉！',
          platform_fit: {
            xiaohongshu: '晨间洗脸仪式感！[Product] 冰淇淋膏体敲治愈🍃 3重泥+4重植萃，洗完超清爽～',
            douyin: '大油田晨间必看！实测8小时控油-66.87%！[Product] 洗完整天不出油！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '大油田的晨间快乐水！挤出来是冰淇淋泥膏🍃', tonePreference: '治愈', commercialScenario: '个人' },
        output: {
          bgm_recommendation: {
            track_name: 'Morning Breeze',
            artist: 'Chillout SoundLab',
            style: ['治愈Lofi', '晨间轻音乐'],
            bpm: '82',
            mood_match: '柔和钢琴与轻盈Lofi鼓点，契合晨间沉浸洗脸场景',
            sync_point: '1.2s(挤膏体), 2.8s(打泡特写)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Pure Water Ambient Glow', style: '纯水声', when_to_use: '适合小红书原声感配音' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '3:4', subtitleStyle: '极简小绿红书体' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 4.0, action: 'subtitle_in', text: '夏天早上起来脸像喷油池？试试晨间清爽 SPA🍃', position: 'bottom_center' },
            { at: '4.0s', startSec: 4.0, endSec: 15.0, action: 'subtitle_in', text: '每次用 [Product]，冰淇淋膏体打出奶油泡沫...', position: 'bottom_center' },
            { at: '15.0s', startSec: 15.0, endSec: 30.0, action: 'subtitle_in', text: 'SGS 实测：8小时控油 -66.87%', position: 'bottom_center' },
            { at: '30.0s', startSec: 30.0, endSec: 45.0, action: 'subtitle_in', text: '洗完水嫩透亮，油皮姐妹快试试～', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_morning_routine.mp4', resolution: '1080x1440', format: 'mp4_h264', duration_sec: 45.0 },
          qa_checklist: ['✓ 晨间自然光视听氛围极佳', '✓ 小红书极简字幕风格优雅', '✓ 零品牌泄漏'],
        },
      },
    }),
    'xiaohongshu',
    'preset_morning_routine',
  ],

  // 4. preset_sgs_science (对应 0716-毛孔.mp4)
  [
    'preset_sgs_science',
    'SGS 科学数据硬核背书',
    'SGS科学背书',
    '对应《0716-毛孔.mp4》实战拆解：微距毛孔吸附，SGS 权威检测报告大字标红背书',
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/0716-毛孔2-1.mp4',
          platform: 'shipinhao',
          bloggerType: 'ingredient_geek',
          viralReason: '3D/微距毛孔吸附原理 + SGS权威报告红字大字标红',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '皮肤科研实验室，高精度皮肤显微镜头与 SGS 权威报告展示',
          subject: 'SGS 报告首页：14天黑头 -35.92%、8小时控油 -66.87% 标红数据',
          style: '硬核科学背书风',
          palette: ['#FF2D55 权威红', '#0A192F 深海蓝', '#FFFFFF 高清白'],
          lighting: '冷感科研发光面板，数据与报告细节清晰度 100%',
          composition: '中央大字数据标红 + 显微微距双重特写',
          mood: '硬核科学，权威不可置疑的信任感',
          camera: '100mm 显微微距 + 静态微动慢推',
          static_image_prompt: 'macro skin pores close up transformation, official clinical test report document with glowing red numbers -35.92%, holding [Product], studio science lighting, 8k resolution',
          rationale: '根据《0716-毛孔.mp4》实战拆解：权威机构 SGS 检测报告大字标红是击穿高客单信任的核心',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '4.0s', shotType: '微距', cameraMovement: '固定镜头', description: '鼻翼毛孔显微放大，油脂堵塞黑头痛点 Hook', mood: '痛点直击' },
            { shotIndex: 2, startTime: '4.0s', endTime: '20.0s', shotType: '特写', cameraMovement: '前推', description: '[Product] 矿物泥微孔结构原理图，吸附毛孔脏污', mood: '科学解析' },
            { shotIndex: 3, startTime: '20.0s', endTime: '45.0s', shotType: '特写', cameraMovement: '静态特写', description: 'SGS 权威检测报告，红字高亮：14天黑头 -35.92%', mood: '权威背书' },
            { shotIndex: 4, startTime: '45.0s', endTime: '67.9s', shotType: '中景', cameraMovement: '慢推', description: '14天前后皮肤通透度真实对比与下单引导', mood: '挂车转化' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '17.0s', pacing: 'medium', narrativeArc: '毛孔痛点显微 Hook -> 矿物泥吸附原理 -> SGS检测红字背书 -> 前后对比挂车', hookTiming: '前4秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“别再用撕拉面膜伤害毛孔了！看看 SGS 权威机构的实测数据！”', sellingPoints: ['SGS 14天黑头-35.92%', 'SGS 8小时控油-66.87%', '三重矿物泥微孔吸附'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '90', musicStyle: '高科技品质Ambient' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'macro skin pores close up...',
          imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
          videoTone: 'brand_tvc',
          durationSec: 5,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'static_micro_motion',
          motion_intensity: 'subtle',
          motion_description: '镜头极其缓慢推进至 SGS 报告大字标红数据与 [Product] 微距瓶身',
          duration_sec: '5',
          video_prompt: 'Ultra macro close up shot skin pore transformation, official SGS report document glowing red text, [Product] science precision aesthetics, 60fps',
          audio_layer: '科技通透 Ambient 音效',
          negative_prompt: '避免报告字迹模糊，避免反射杂光',
          isMultiShot: true,
          shotPrompts: [
            'Microscope lens view on nose skin pores showing oil reduction',
            '3D science diagram of active ingredient deep cleansing pore',
            'Official SGS report paper with glowing red text overlay',
            'Smooth slow push on clean glowing face holding product',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'Ultra macro close up shot skin pore...', targetPlatform: 'shipinhao', scriptPersona: '成分党' },
        output: {
          title: '毛孔粗大还爱长黑头？SGS 权威实测：14天黑头 -35.92%！📊',
          hook: '别再瞎用撕拉面膜了！看看权威机构 SGS 的实测报告！',
          body: '用 [Product]，三重矿物泥像毛孔磁铁，把深层油脂黑头通通吸走！\n\nSGS 权威实测 8小时控油 -66.87%，14天黑头少 -35.92%！数据标红背书，成分党放心用～',
          hashtags: ['#SGS权威检测', '#去黑头洗面奶', '#毛孔收敛', '#硬核科普'],
          cta: '点击下方购买链接，直达官方旗舰店！',
          platform_fit: {
            shipinhao: '国货品质认证！[Product] 获 SGS 权威认证，14天黑头-35.92%，温和去黑头不伤肤！',
            douyin: '黑头党狂喜！SGS权威实测14天黑头少35.92%！[Product] 买一送一速抢！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '毛孔粗大还爱长黑头？SGS 权威实测：14天黑头 -35.92%！📊', tonePreference: '高级', commercialScenario: '抖音/小红书商业化' },
        output: {
          bgm_recommendation: {
            track_name: 'Deep Focus Luxury Ambient',
            artist: 'Zenith Sound',
            style: ['品质Ambient', '科技通透'],
            bpm: '90',
            mood_match: '冷静沉稳的科技声效，突显SGS权威检测报告与微距毛孔吸附过程',
            sync_point: '1.0s(毛孔微距), 3.5s(SGS报告弹出)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Crystal Clear Water Ambience', style: '水感轻音乐', when_to_use: '适合高品质展现' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '白字柔影' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 4.0, action: 'subtitle_in', text: '别再用撕拉面膜伤害毛孔了！看看 SGS 权威报告！', position: 'bottom_center' },
            { at: '4.0s', startSec: 4.0, endSec: 20.0, action: 'subtitle_in', text: '[Product] 三重矿物泥微孔吸附，温和吸走黑头油脂', position: 'bottom_center' },
            { at: '20.0s', startSec: 20.0, endSec: 45.0, action: 'brand_stamp', text: 'SGS 权威机构实测认证', position: 'top_right' },
            { at: '45.0s', startSec: 45.0, endSec: 67.9, action: 'subtitle_in', text: 'SGS实测：14天黑头 -35.92%！', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_sgs_science.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 67.9 },
          qa_checklist: ['✓ SGS权威报告红字高清可读', '✓ 科技感字幕样式符合高端风格', '✓ 零品牌泄漏'],
        },
      },
    }),
    'shipinhao',
    'preset_sgs_science',
  ],

  // 5. preset_128bpm_beat (对应 李响-018.mp4)
  [
    'preset_128bpm_beat',
    '128BPM 卡点极速测评',
    '128BPM卡点道具',
    '对应《李响-018.mp4》实战拆解：3cm 刻度尺/具象测量道具对比，128BPM 重低音强卡点节奏',
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/李响-018-0706- 三厘米（换画面）.mp4',
          platform: 'douyin',
          bloggerType: 'review_beauty',
          viralReason: '3cm刻度尺具象测量道具 + 128BPM重低音卡点极速切镜头',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '高对比度测评拍摄台，手持 3cm 刻度尺具象测量道具与 [Product]',
          subject: '刻度尺精准测量膏体挤出量与泡沫丰富度',
          style: '极速卡点道具测评风',
          palette: ['#00E5FF 极速蓝', '#FFCC00 刻度黄', '#121212 炫酷黑'],
          lighting: '多角度高频闪光/快节奏切变光',
          composition: '具象道具居中切变 + 镜头极速缩放',
          mood: '极速刺激，快节奏高爆完播',
          camera: '快切镜头 (Whip Pan) + 极速打卡卡点',
          static_image_prompt: 'holding 3cm measurement ruler prop next to [Product] cleanser tube, fast pacing review setup, vivid color contrast, high dynamic range, 4k 60fps',
          rationale: '根据《李响-018.mp4》实战拆解：3cm刻度尺等具象道具建立极强认知，配合128BPM音乐实现秒秒卡点',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '3.0s', shotType: '特写', cameraMovement: '快切前推', description: '3cm 刻度尺测量道具快切 Hook，“拿刻度尺测过的都知道！”', mood: '道具震撼' },
            { shotIndex: 2, startTime: '3.0s', endTime: '15.0s', shotType: '近景', cameraMovement: '左右甩镜', description: '128BPM 重低音卡点，[Product] 膏体秒挤打泡切变', mood: '极速卡点' },
            { shotIndex: 3, startTime: '15.0s', endTime: '35.0s', shotType: '特写', cameraMovement: '快切', description: '吸油纸贴脸 3 秒秒干哑光，刻度对比出油差异', mood: '硬核证明' },
            { shotIndex: 4, startTime: '35.0s', endTime: '50.0s', shotType: '特写', cameraMovement: '固定镜头', description: 'SGS 8小时控油 -66.87% 卡点图表弹出', mood: '数据硬核' },
            { shotIndex: 5, startTime: '50.0s', endTime: '65.6s', shotType: '中景', cameraMovement: '前推', description: '极速引导点击左下角挂车下订单', mood: '强转化' },
          ],
          videoStructure: { totalShots: 5, avgShotDuration: '13.12s', pacing: 'fast', narrativeArc: '3cm道具Hook -> 128BPM卡点打泡 -> 吸油纸极速实测 -> SGS数据卡点 -> 左下角挂车', hookTiming: '前3秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“3厘米具象测试！128BPM 卡点实测这支神仙洗面奶！”', sellingPoints: ['3cm刻度尺具象测试', '128BPM重低音卡点', 'SGS 8小时控油-66.87%'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '128', musicStyle: '128BPM重低音Trap' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'holding 3cm measurement ruler prop...',
          imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
          videoTone: 'douyin_beat',
          durationSec: 5,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'pan_right',
          motion_intensity: 'strong',
          motion_description: '镜头极速横移并卡点对焦 3cm 刻度尺与 [Product] 膏体',
          duration_sec: '5',
          video_prompt: 'Fast dynamic camera cuts, 3cm ruler prop measurement, 128BPM beat sync with [Product] lathering, fast blur transitions, 60fps',
          audio_layer: '128BPM 重低音卡点音效',
          negative_prompt: '避免镜头掉帧，避免画面脱焦',
          isMultiShot: true,
          shotPrompts: [
            'Fast camera zoom on 3cm ruler measurement prop',
            'Speed ramp close up of [Product] foaming rich lather',
            'Whip pan to oily face vs matte clean face test with blot paper',
            'Card pop graphics of SGS test report numbers matching beat drop',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'Fast dynamic camera cuts, 3cm ruler prop...', targetPlatform: 'douyin', scriptPersona: '成分党' },
        output: {
          title: '3厘米具象测试！128BPM 卡点实测这支神仙 [Product]！⚡',
          hook: '拿刻度尺测过的都知道！到底有多惊艳？',
          body: '128BPM 快节奏实测！用 3cm 具象道具直观证明 [Product] 的深层清爽度！\n\nSGS 机构认证 8小时控油 -66.87%，卡点画面帧帧震撼，大油田闭眼入！',
          hashtags: ['#128BPM卡点', '#硬核测评', '#控油洗面奶', '#油皮神器'],
          cta: '点击左下角挂车，秒抢买一送一福利！',
          platform_fit: {
            douyin: '128BPM重低音极速卡点！3cm具象道具测试证明：[Product] 8小时控油-66.87%！速抢！',
            xiaohongshu: '拿刻度尺测过的都知道！[Product] 极速打泡沉浸感，油皮用了真香～',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '3厘米具象测试！128BPM 卡点实测这支神仙 [Product]！⚡', tonePreference: '卡点', commercialScenario: '抖音/小红书商业化' },
        output: {
          bgm_recommendation: {
            track_name: 'Electro Drop Bass Boost 130BPM',
            artist: 'Cyber Synth',
            style: ['卡点Electronic', '重低音Trap'],
            bpm: '128',
            mood_match: '128BPM重低音卡点，精准匹配刻度尺具象道具快切与打泡镜头',
            sync_point: '0.8s(道具快切), 2.4s(卡点打泡), 4.8s(数据标红)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Trap Tech Beat 128BPM', style: 'Phonk Trap', when_to_use: '适合极端重低音需求' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '黄字黑边' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 3.0, action: 'subtitle_in', text: '3厘米具象测试！拿刻度尺测过的都知道！', position: 'bottom_center' },
            { at: '3.0s', startSec: 3.0, endSec: 15.0, action: 'subtitle_in', text: '128BPM 重低音卡点实测：[Product] 极致打泡！', position: 'bottom_center' },
            { at: '15.0s', startSec: 15.0, endSec: 35.0, action: 'subtitle_in', text: 'SGS 权威认证：8小时控油 -66.87%', position: 'bottom_center' },
            { at: '35.0s', startSec: 35.0, endSec: 65.6, action: 'subtitle_in', text: '点击左下角挂车，抢买一送一专享！', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_128bpm_beat.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 65.6 },
          qa_checklist: ['✓ 128BPM音画重低音卡点极强', '✓ 具象道具3cm文字标出', '✓ 零品牌泄漏'],
        },
      },
    }),
    'douyin',
    'preset_128bpm_beat',
  ],

  // 6. preset_emotional_story (对应 郭海艳-去年的我.mp4)
  [
    'preset_emotional_story',
    '前后蜕变叙事与情绪共鸣',
    '前后蜕变共鸣',
    '对应《郭海艳-去年的我.mp4》实战拆解：第一人称 Vlog，“去年的我 vs 现在的我”真实皮肤蜕变共鸣',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/郭海艳-0709-43-去年的我1.mp4',
          platform: 'xiaohongshu',
          bloggerType: 'daily_seeding',
          viralReason: '第一人称情感共鸣 Vlog + 前后皮肤蜕变真实照片',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '温馨卧室/梳妆台第一人称视角，展示去年的素颜痛点老照片',
          subject: '博主手持 [Product] 记录肌肤 365 天真实蜕变',
          style: '第一人称情感 Vlog 风',
          palette: ['#FFB6C1 暖粉', '#FFF5EE 柔暖', '#4A4A4A 质感灰'],
          lighting: '温馨暖色窗边自然光，营造真实亲切感',
          composition: '第一人称视角 + 老照片画中画对比',
          mood: '真情实意，强烈情绪共鸣与陪伴感',
          camera: '手持微晃慢拉 (Zoom Out) + 怀旧色彩过渡',
          static_image_prompt: 'first person lifestyle vlog photo holding old picture showing oily skin contrast with current glowing healthy face holding [Product], warm natural light, 4k',
          rationale: '根据《郭海艳-去年的我.mp4》实战拆解：故事化叙事能建立极高用户黏性与情感共鸣',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '6.0s', shotType: '中景', cameraMovement: '慢推', description: '博主翻看去年的老照片，满脸油光痘痘，“去年的我真的好自卑...”', mood: '回忆共鸣' },
            { shotIndex: 2, startTime: '6.0s', endTime: '25.0s', shotType: '近景', cameraMovement: '平移', description: '遇到 [Product] 后的日常坚持洗护，冰淇淋膏体抚平焦虑', mood: '陪伴蜕变' },
            { shotIndex: 3, startTime: '25.0s', endTime: '55.0s', shotType: '特写', cameraMovement: '轻微上抬', description: '现在的皮肤哑光水润通透，SGS 实测 14 天黑头 -35.92%', mood: '自信喜悦' },
            { shotIndex: 4, startTime: '55.0s', endTime: '78.3s', shotType: '中景', cameraMovement: '固定', description: '真情实感向有同样困扰的姐妹真心推荐', mood: '真诚种草' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '19.57s', pacing: 'medium', narrativeArc: '过去痛苦记忆Hook -> 转折契机遇见 -> 皮肤蜕变过程 -> 情绪共鸣分享', hookTiming: '前6秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“翻到去年这时候的照片...真的不敢相信我坚持了下来！”', sellingPoints: ['去年的我vs现在的我对比', 'SGS 14天黑头-35.92%', '温和养肤不紧绷'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '95', musicStyle: '温情生活R&B' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'first person lifestyle vlog photo...',
          imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
          videoTone: 'xiaohongshu_healing',
          durationSec: 4,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'zoom_out',
          motion_intensity: 'medium',
          motion_description: '镜头由老照片缓缓后撤，展现博主手持 [Product] 的水润自信笑容',
          duration_sec: '4',
          video_prompt: 'First person emotional vlog camera movement, transition from past skin struggle to current healthy clear skin holding [Product], warm cinematic tones, 60fps',
          audio_layer: '舒缓 R&B 旋律 + 人声真情朗诵',
          negative_prompt: '避免色彩过冷，避免夸张特效',
          isMultiShot: true,
          shotPrompts: [
            'Slow zoom out on old photo held in hand showing past oily skin',
            'Hand holding [Product] in warm bathroom morning light',
            'Extreme macro on smooth clear skin texture with gentle smile',
            'Medium shot of blogger talking warmly to camera with product',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: 'First person emotional vlog camera...', targetPlatform: 'xiaohongshu', scriptPersona: '油皮亲妈' },
        output: {
          title: '去年的我 vs 现在的我...记录皮肤蜕变的 365 天！💖',
          hook: '翻到去年这时候的照片，真的差点没认出来自己...',
          body: '曾经因为油光满面不敢抬头，直到遇见了 [Product]...\n\n坚持使用后，出油和黑头问题明显改善。SGS 实测 14天黑头少 -35.92%！希望每个姐妹都能找回自信好皮肤～',
          hashtags: ['#皮肤蜕变', '#去年的我', '#护肤Vlog', '#控油心得'],
          cta: '姐妹们有什么护肤困扰，评论区告诉我！',
          platform_fit: {
            xiaohongshu: '去年的我vs现在的我！[Product] 真的陪我走过了最难的时期，油皮姐妹放心冲～',
            douyin: '真实蜕变纪录片！[Product] 陪我打赢皮肤翻身仗！SGS实测14天黑头-35.92%！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '去年的我 vs 现在的我...记录皮肤蜕变的 365 天！💖', tonePreference: '治愈', commercialScenario: '个人' },
        output: {
          bgm_recommendation: {
            track_name: 'Chill Sunset R&B Routine',
            artist: 'Smooth Grooves',
            style: ['节奏R&B', '生活方式', '情绪共鸣'],
            bpm: '95',
            mood_match: '温暖沉静的R&B旋律，完美融合前后蜕变叙事与真情实感口播',
            sync_point: '1.5s(旧照片展现), 5.0s(蜕变后笑容)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Lofi Rain Coffee & Skincare', style: '治愈Lofi', when_to_use: '适合偏静谧独白' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '3:4', subtitleStyle: '极简小绿红书体' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 6.0, action: 'subtitle_in', text: '翻到去年这时候的照片，真的差点没认出来自己...', position: 'bottom_center' },
            { at: '6.0s', startSec: 6.0, endSec: 25.0, action: 'subtitle_in', text: '曾经因为油光蛮自卑，直到遇见了 [Product]...', position: 'bottom_center' },
            { at: '25.0s', startSec: 25.0, endSec: 55.0, action: 'subtitle_in', text: 'SGS 实测：14天黑头少 -35.92%', position: 'bottom_center' },
            { at: '55.0s', startSec: 55.0, endSec: 78.3, action: 'subtitle_in', text: '愿每个姐妹都能找回自信好皮肤💖', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_emotional_story.mp4', resolution: '1080x1440', format: 'mp4_h264', duration_sec: 78.3 },
          qa_checklist: ['✓ 情感氛围拉满', '✓ 字幕位置优雅不挡画面', '✓ 零品牌泄漏'],
        },
      },
    }),
    'xiaohongshu',
    'preset_emotional_story',
  ],

  // 7. preset_brand_trust (对应沙利文第一认证案例)
  [
    'preset_brand_trust',
    '品质信任品牌故事',
    '品质信任品牌',
    '对应沙利文第一认证真实案例：高级暗调光影，沙利文行业第一认证与全网销量权威背书',
    'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/刘恋-0714-84杨穆吴徐陈赵蔡.mp4',
          platform: 'shipinhao',
          bloggerType: 'skincare_expert',
          viralReason: '沙利文行业第一权威认证 + 高奢暗调光影 + 销量破3000万背书',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '高奢暗调实验室/展览台，金色光影轮廓勾勒 [Product] 瓶身',
          subject: '沙利文 (Frost & Sullivan) 市场销量第一官方证书特写',
          style: '高奢品牌 TVC 信任风',
          palette: ['#D4AF37 奢华金', '#111827 经典黑', '#FFFFFF 亮白'],
          lighting: '顶级影视 45度轮廓金光，边缘光影极具高级感',
          composition: '中心对称构图 + 360度金光环绕',
          mood: '尊贵权威，极高品质信任',
          camera: '360度环绕旋转 (Rotate) + 慢速下移',
          static_image_prompt: 'luxury premium skincare product shot [Product], studio dark moody lighting with golden rim lights, Frost and Sullivan market leader certificate background, 8k',
          rationale: '根据沙利文第一认证实战拆解：权威第一证书 + 极致奢华光影能建立品牌壁垒',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '5.0s', shotType: '特写', cameraMovement: '慢推', description: '沙利文官方认证奖牌金色烫印特写 Hook，“连续2年行业销量第一”', mood: '权威震撼' },
            { shotIndex: 2, startTime: '5.0s', endTime: '20.0s', shotType: '微距', cameraMovement: '360度旋转', description: '[Product] 膏体质感与金色光影环绕展览', mood: '高奢质感' },
            { shotIndex: 3, startTime: '20.0s', endTime: '45.0s', shotType: '特写', cameraMovement: '静态特写', description: 'SGS 8小时控油 -66.87% 数据与研发实验室背景', mood: '科研硬核' },
            { shotIndex: 4, startTime: '45.0s', endTime: '75.0s', shotType: '中景', cameraMovement: '慢退', description: '全网热销 3000 万支口碑汇总与品质保障声明', mood: '信任成交' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '18.75s', pacing: 'slow', narrativeArc: '沙利文第一证书Hook -> 360度高奢光影 -> SGS科研数据 -> 全网销量口碑成交', hookTiming: '前5秒' },
          originalScript: { hasVoiceover: true, estimatedScript: '“连续2年全国销量第一！沙利文官方权威认证的实力！”', sellingPoints: ['沙利文第一认证', 'SGS 8小时控油-66.87%', '全网热销 3000 万支'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '65', musicStyle: '高级奢华Ambient' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: 'luxury premium skincare product shot...',
          imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=600&q=80',
          videoTone: 'brand_tvc',
          durationSec: 5,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'rotate',
          motion_intensity: 'subtle',
          motion_description: '镜头 360 度缓慢旋转打光，金色轮廓光沿 [Product] 瓶身流动',
          duration_sec: '5',
          video_prompt: '360 degree slow cinematic rotation around [Product] luxury bottle, dark moody lighting with golden highlight rim lights, Frost & Sullivan certificate background, 8k',
          audio_layer: '高级管弦 Ambient 配乐',
          negative_prompt: '避免过曝，避免镜头晃动',
          isMultiShot: true,
          shotPrompts: [
            'Golden close up of official Frost & Sullivan market leader seal',
            '360 rotation around [Product] with studio rim lighting',
            'Science lab test tubes with glowing HUD oil reduction data',
            'Wide shot of product lineup with elegant golden brand backdrop',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: '360 degree slow cinematic rotation...', targetPlatform: 'shipinhao', scriptPersona: '高级感沉浸' },
        output: {
          title: '连续2年行业销量第一！沙利文权威认证的品质保障 🏆',
          hook: '为什么全网数千万人都在选择 [Product]？',
          body: '沙利文官方权威认证！连续 2 年全国销量第一品牌背书！\n\n以极致严谨的科学研发标准打造 [Product]，SGS 实测 8小时控油 -66.87%。品质信任，选它不踩雷！',
          hashtags: ['#沙利文第一认证', '#品质国货', '#销量冠军', '#品牌故事'],
          cta: '点击下方了解品牌故事与官方礼遇！',
          platform_fit: {
            shipinhao: '国货品质之选！[Product] 获沙利文官方认证全国销量第一，SGS实测控油-66.87%！',
            douyin: '爆款背后的硬核实力！沙利文第一认证 [Product]，买一送一尊享礼遇！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '连续2年行业销量第一！沙利文权威认证的品质保障 🏆', tonePreference: '高级', commercialScenario: '抖音/小红书商业化' },
        output: {
          bgm_recommendation: {
            track_name: 'Deep Focus Luxury Ambient',
            artist: 'Zenith Sound',
            style: ['品质Ambient', '高级清透'],
            bpm: '65',
            mood_match: '庄重优雅的大片音乐，强调沙利文销量第一与品牌品质背书',
            sync_point: '1.2s(沙利文证书), 4.0s(产品高光)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Pure Water Ambient Glow', style: '纯净通透', when_to_use: '适合高端宣导' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '白字柔影' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 5.0, action: 'brand_stamp', text: '沙利文官方认证全国销量第一', position: 'top_right' },
            { at: '0.0s', startSec: 0, endSec: 5.0, action: 'subtitle_in', text: '为什么全网数千万人都在选择 [Product]？', position: 'bottom_center' },
            { at: '5.0s', startSec: 5.0, endSec: 20.0, action: 'subtitle_in', text: '沙利文权威认证：连续2年全国销量第一！', position: 'bottom_center' },
            { at: '20.0s', startSec: 20.0, endSec: 45.0, action: 'subtitle_in', text: 'SGS 权威实测：8小时控油 -66.87%', position: 'bottom_center' },
            { at: '45.0s', startSec: 45.0, endSec: 75.0, action: 'subtitle_in', text: '品质信任，认准正品保障！', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_brand_trust.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 75.0 },
          qa_checklist: ['✓ 沙利文第一品牌印章完美悬挂', '✓ 画面具备 TVC 级暗调高级质感', '✓ 零品牌泄漏'],
        },
      },
    }),
    'shipinhao',
    'preset_brand_trust',
  ],

  // 8. preset_asmr_macro (对应 黎晓晓-0704.mp4)
  [
    'preset_asmr_macro',
    'ASMR 极致微距质感展示',
    'ASMR微距质感',
    '对应《黎晓晓-0704.mp4》实战拆解：60FPS 超流畅微距摄影，纯水滴/膏体音效沉浸',
    'https://images.unsplash.com/photo-1512290900673-7002fffe929a?auto=format&fit=crop&w=600&q=80',
    JSON.stringify({
      step1: {
        status: 'completed',
        inputs: {
          mediaUrl: 'uploads/materials/黎晓晓-0704-157-AI歌曲高考主题优化.mp4',
          platform: 'xiaohongshu',
          bloggerType: 'daily_seeding',
          viralReason: '60FPS高帧率超微距 + 纯物理ASMR水滴泡沫音效',
          imageModel: 'GPT Image 1',
        },
        output: {
          scene: '60FPS 极速摄影棚，晶莹水滴飞溅与 [Product] 膏体触碰',
          subject: '微距镜头下水滴在 [Product] 膏体表面弹跳破裂特写',
          style: '60FPS 极速 ASMR 质感风',
          palette: ['#E0F7FA 水晶蓝', '#FFFFFF 纯白', '#004D40 幽深绿'],
          lighting: '4,000Hz 极速摄影无频闪高透强光',
          composition: '极近微距 + 水滴爆破瞬间居中',
          mood: '极致沉浸解压，视听双重享受',
          camera: 'Phantom 60FPS 超高速慢动作镜头',
          static_image_prompt: '60fps high frame rate macro photo of water droplets splashing on [Product] smooth surface, texture close up, crystal clear lighting, 8k',
          rationale: '根据《黎晓晓-0704.mp4》实战拆解：60FPS的高流畅视觉与ASMR结合，能给观看者带来极度愉悦的解压感',
          shotList: [
            { shotIndex: 1, startTime: '0.0s', endTime: '4.0s', shotType: '微距', cameraMovement: '静态微动', description: '60FPS 高帧率水滴在 [Product] 膏体表面飞溅破裂 Hook', mood: '解压Hook' },
            { shotIndex: 2, startTime: '4.0s', endTime: '12.0s', shotType: '微距', cameraMovement: '慢推', description: '超微距膏体拉丝与磨砂微颗粒纹理展示', mood: '极致纹理' },
            { shotIndex: 3, startTime: '12.0s', endTime: '22.0s', shotType: '特写', cameraMovement: '固定镜头', description: 'ASMR 泡沫破裂声音效，绵密奶油泡沫包覆肌肤', mood: '听觉沉浸' },
            { shotIndex: 4, startTime: '22.0s', endTime: '32.3s', shotType: '近景', cameraMovement: '轻微后退', description: '清水瞬间冲洗干净，呈现无瑕哑光水透感', mood: '清爽净澈' },
          ],
          videoStructure: { totalShots: 4, avgShotDuration: '8.07s', pacing: 'fast', narrativeArc: '60FPS水滴爆破Hook -> 超微距膏体纹理 -> ASMR泡沫触感 -> 清爽洁净触达', hookTiming: '前4秒' },
          originalScript: { hasVoiceover: false, estimatedScript: '“【ASMR】60FPS 极致微距质感体验，戴上耳机享受！”', sellingPoints: ['60FPS超流畅高帧率', '纯水滴ASMR音效', '极致丝滑触感'] },
          audioAnalysis: { hasBgm: true, estimatedBpm: '0', musicStyle: 'ASMR纯水滴与泡泡音效' },
        },
      },
      step2: {
        status: 'completed',
        inputs: {
          static_image_prompt: '60fps high frame rate macro photo...',
          imageUrl: 'https://images.unsplash.com/photo-1512290900673-7002fffe929a?auto=format&fit=crop&w=600&q=80',
          videoTone: 'xiaohongshu_healing',
          durationSec: 4,
          videoModel: 'Seedance 2.0 Fast',
        },
        output: {
          motion_type: 'static_micro_motion',
          motion_intensity: 'subtle',
          motion_description: '60FPS 极速摄影，镜头捕捉水滴在 [Product] 膏体表面极慢破裂',
          duration_sec: '4',
          video_prompt: '60FPS high frame rate ultra macro shot, water droplets bouncing on [Product] smooth surface, texture close up, ASMR sound immersion, crystal clear lighting, 8k ultra detailed',
          audio_layer: '纯物理水滴与泡泡 ASMR 音效',
          negative_prompt: '避免画质模糊，避免音乐噪声',
          isMultiShot: true,
          shotPrompts: [
            '60FPS phantom camera macro shot of water drop hitting product surface',
            'Slow motion texture stretch of creamy mint cleanser',
            'Microscope view of dense micro bubbles popping in slow motion',
            'Clean water splash rinsing off skin leaving matte finish',
          ],
        },
      },
      step3: {
        status: 'completed',
        inputs: { videoPrompt: '60FPS high frame rate ultra macro shot...', targetPlatform: 'xiaohongshu', scriptPersona: '高级感沉浸' },
        output: {
          title: '声音带耳机！【ASMR】60FPS 极致微距质感体验 🎧',
          hook: '戴上耳机，听听真正的物理沉浸解压！',
          body: '全过程 60FPS 高帧率极速微距拍摄！体验 [Product] 的极致丝滑触感与绵密泡泡 ASMR 音效...\n\n视觉与听觉的双重享受，触感温和净澈，瞬间带来极致舒爽！',
          hashtags: ['#ASMR', '#60FPS', '#极致微距', '#解压洗脸'],
          cta: '戴耳机听的姐妹，评论区打个 1！',
          platform_fit: {
            xiaohongshu: '【ASMR沉浸】60FPS极致微距！[Product] 水滴飞溅与泡泡音效敲解压～',
            douyin: '戴耳机听！60FPS高帧率微距实测 [Product]，视听双重沉浸体验！',
          },
        },
      },
      step4: {
        status: 'completed',
        inputs: { copywritingTitle: '声音带耳机！【ASMR】60FPS 极致微距质感体验 🎧', tonePreference: '治愈', commercialScenario: '个人' },
        output: {
          bgm_recommendation: {
            track_name: 'ASMR Pure Water Droplets & Texture',
            artist: 'Sound Nature Lab',
            style: ['ASMR/纯音效', '极致沉浸'],
            bpm: '0',
            mood_match: '零音乐干扰，纯物理水滴与泡泡细腻破裂声音效，强化60FPS微距视觉',
            sync_point: '0.5s(水滴飞溅), 2.0s(膏体拉丝音)',
            license_note: '已商业授权',
          },
          alternatives: [{ track_name: 'Pure Water Ambient Glow', style: '柔水背景', when_to_use: '适合偏音乐感ASMR' }],
        },
      },
      step5: {
        status: 'completed',
        inputs: { aspectRatio: '9:16', subtitleStyle: '极简小绿红书体' },
        output: {
          timeline: [
            { at: '0.0s', startSec: 0, endSec: 4.0, action: 'subtitle_in', text: '🎧 建议戴上耳机，体验 60FPS ASMR 沉浸解压', position: 'bottom_center' },
            { at: '4.0s', startSec: 4.0, endSec: 12.0, action: 'subtitle_in', text: '[Product] 超微距膏体触感与细腻颗粒', position: 'bottom_center' },
            { at: '12.0s', startSec: 12.0, endSec: 22.0, action: 'subtitle_in', text: '绵密奶油泡泡破裂声 ASMR', position: 'bottom_center' },
            { at: '22.0s', startSec: 22.0, endSec: 32.3, action: 'subtitle_in', text: '清水冲洗瞬间，带来极度舒适清爽', position: 'bottom_center' },
          ],
          output: { filename: 'v_preset_asmr_macro.mp4', resolution: '1080x1920', format: 'mp4_h264', duration_sec: 32.3 },
          qa_checklist: ['✓ 60FPS微距视觉极致清晰', '✓ ASMR音效纯净无噪', '✓ 零品牌泄漏'],
        },
      },
    }),
    'xiaohongshu',
    'preset_asmr_macro',
  ],
];
